### ISSUE TITLE
Question: When will the new version be released?

### ISSUE THREAD

**Issue by Apollo122** [LiquidPlayer/LiquidCore#130]
First of all thank you for this library. It's pretty useful.
Problem is I really need https://github.com/LiquidPlayer/LiquidCore/issues/117 fix in my android project. Could you please give an estimate date for the next version which includes this fix?
https://github.com/LiquidPlayer/LiquidCore/issues/117

**Comment by ericwlange** [comment]
@Apollo122 I wasn't planning on putting out a 0.6.3 release unless there was something major that needed to go in quickly.  I am focused on 0.7.0, which upgrades from node 8.9 -> 10.15 and is a lot of work and will take more time.

Is there a reason you need this released and not just [build it yourself](https://github.com/LiquidPlayer/LiquidCore/tree/master/LiquidCoreAndroid#building-the-liquidcore-android-library) from source?

If for some reason, you want jitpack to do the build for you, see the [jitpack docs](https://jitpack.io/docs/).  You can tell it to use the version at master instead of a release tag.  See the section on snapshots.

**Comment by Apollo122** [comment]
Tried the jitpack solution but got error.
Added JitPack maven repository to the list of repositories like this

maven { url 'https://jitpack.io' }

Then added to dependency like this:

implementation 'com.github.LiquidPlayer:LiquidCore:master-SNAPSHOT'

But getting an error:

ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.LiquidPlayer:LiquidCore:master-SNAPSHOT.

Any ideas?

**Comment by ericwlange** [comment]
Yes, I can see the error log that it failed.  Try:

```
implementation 'com.github.LiquidPlayer.LiquidCore:LiquidCore:4aca87d055'
```

That commit should include this fix.

**Comment by Apollo122** [comment]
Thanks it works now. And the solution fixed my problem.
