### ISSUE TITLE
Unresolved reference: StartServiceListener

### ISSUE THREAD

**Issue by CaliforniaMountainSnake** [LiquidPlayer/LiquidCore#132]
I just try to create a MicroService according instructions from the README (https://github.com/LiquidPlayer/LiquidCore/tree/master/LiquidCoreAndroid#the-microservice).
And this code fails, because the StartServiceListener() method doesn't exist in MicroService class.

MicroService.on() method doesn't exist too. Apparently is has been renamed to addEventListener().
How can I create a working MicroService?

**Comment by ericwlange** [comment]
@CaliforniaMountainSnake Thanks for pointing this out, and I am surprised that nobody has ever reported this before.  These are just typos:

`StartServiceListner()` _should be_ `ServiceStartListener()` (this is correct elsewhere in the doc)
and
`MicroService.on()` _should be_ `MicroService.addEventListener()`.

These have been fixed in the README.
