### ISSUE TITLE
Requiring another js file from resources

### ISSUE THREAD

**Issue by sohayb** [LiquidPlayer/LiquidCore#146]
Hello,
In my Android app, I'm starting a `js` file from the `res/raw` folder as a MicroService, In that file, I'm importing `js` library from the same folder but it's not working.
I tried 2 different approaches:
```javascript
const converter = require('./converter')
```
```javascript
const converter = require('android.resource://org.liquidplayer.helloworld/raw/converter')
```
Please note that when running those `js` files on the dev machine, the first way obviously works, but on Android it doesn't. Any help on how to do this?
Please note that when I tried the other approach of just loading the library into a `JSContext`, I got an exception `Reference Error: module is not defined`
```kotlin
val jsVal = assets.open("converter.js").use {
    it.bufferedReader().readLines().reduce { acc, s ->  "$acc\n$s"}
}
context.evaluateScript(jsVal)
```

**Comment by ericwlange** [comment]
@sohayb Node.js in LiquidCore cannot access resources directly.  This is intentional.  To `require` other js files, you must use a bundler. [`liquidcore-cli`](https://github.com/LiquidPlayer/liquidcore-cli) has this feature.  See the [Hello World tutorial](https://github.com/LiquidPlayer/LiquidCore/blob/master/doc/AndroidREADME.md#hallo-die-weld-micro-service-tutorial) for info on how to install it.  To create the bundle, you can use:

```bash
npm run bundler -- --platform=android --entry-file=MyEntryJSFile.js --bundle-output=MyBundledFile.js
```

If you required another file (e.g. `converter.js`), it will get bundled into `MyBundledFile.js` and work as you expect.

**Comment by sohayb** [comment]
Thanks a lot @ericwlange . Will try that out and let you know and close this ticket 👍

**Comment by sohayb** [comment]
This worked perfectly, thanks 🙌
