### ISSUE TITLE
Allow usage of LiquidCoreAndroid with minSdkVersion = 16

### ISSUE THREAD

**Issue by martinspaeth** [LiquidPlayer/LiquidCore#19]
Hi there, 
and thank you for the great work you published here!

I am currently tinkering around with the LiquidCore for a projekt and it seems very promising.

While testing on a bunch of devices i run into a libc error which where fixed with the last release.

Since the project targets devices with sdkVersion >= 16 i am not able to update to the current version. 

In the change log i can't find a change in LiquidCoreAndroid that requires minSdkVersion 17:
https://github.com/LiquidPlayer/LiquidCore/commit/78edf66cb8effd635e3ed7c1736d6060b14420f3

Any chance to decrement the minSdkVersion for LiquidCoreAndroid only?

Best regards
Martin

**Comment by ericwlange** [comment]
It is possible to use it with minSdkVersion = 16.  In fact, that's where I originally had it.  But at one point I wanted to use one single method that was only available with 17.  But I have since decided against using that method.  I changed it back to 16 locally and it builds fine, so you can feel free to do that on your local repo.  I will include this in the next release.

**Comment by ericwlange** [comment]
Fixed in [3e80cd53b853be0b26cbe935189a1624b7cfc19c](https://github.com/LiquidPlayer/LiquidCore/commit/3e80cd53b853be0b26cbe935189a1624b7cfc19c)

**Comment by ericwlange** [comment]
This is fixed in Release 0.2.2
