### ISSUE TITLE
What's the status on the iOS port?

### ISSUE THREAD

**Issue by 540Grunkspin** [LiquidPlayer/LiquidCore#42]
With the risk of being really annoying I would just like to ask: What's the status for the iOS port of this project?

**Comment by ericwlange** [comment]
Not annoying at all.  I'm glad see there's demand.

Short answer: it is in the planning stages, but is an epic project that is going to take a long time, given I am a lone developer working on this on nights and weekends.

Aside from just having to get it up and running in a different language, the main blocker is an Apple rule.  For whatever reason, Apple will not allow any dynamic code generation that isn't done through it own JavaScript engine, JavaScriptCore.  So V8 is verboten.  Interestingly, even Google Chrome on iOS uses JavaScriptCore in WebKit, not V8 -- even in the browser it was designed for.  Any attempts to use other engines will get your app declined in the App Store.  Unfortunately, Node.js is deeply intertwined with V8, which creates a problem.

There are 3 options:

1. Port V8 to iOS anyway.  Given that it does build for OSX, presumably it wouldn't be too hard to get it to compile and run.  This would allow everything to work smoothly like it does for Android.  The downside is that it would only be suitable for apps deployed outside of the App Store.  This is a non-starter for me, given my goal for the project.

2. Replace the V8 API calls in Node with equivalent calls to JavaScriptCore.  This is doable, although a lot of work.  The downside is that it isn't scalable.  I've taken great pains to make as few changes to the node codebase as possible so that when significant newer versions are released, it only takes a weekend to integrate, and to minimize the introduction of bugs.  This would completely kill my ability to do that.  So it is not a preferred option.

3. Write a V8 -> JSC shim which mimics the V8 API and translates it JavaScriptCore.  I have already [done this in reverse](https://github.com/LiquidPlayer/LiquidCore/tree/master/LiquidCoreAndroid/src/main/cpp/JSC), as I wanted to support React Native running on top of LiquidCore -- which now works, btw.  React Native is deeply intertwined with JSC, and following the same principle of modifying as little code as possible, this was the most extensible way to do this.  However, this was manageable because the JSC API is rather straightforward.  V8 is not.  It will take a ton of work to achieve this and long time, given I have no help.

I don't see a good alternative beyond choice 3.  The only other option is a kind of "poor man's Node" which just implements the most basic shim, but again I would be taking a snapshot in time and it would be very difficult to keep moving with all of the cool stuff the node community comes up with.  So given that, I will probably start experimenting with option 3 once version 0.4.x has stabilized for Android.  This Android version will be quite good for the foreseeable future, so I can hopefully begin focusing on iOS.

So long answer -- the timeframe does not look good, but I do plan to start working on it soon.

**Comment by ericwlange** [comment]
For those who are following this, experimental support of iOS is now working.  I am still in the process of writing documentation, but if you want to play with it, you can either open the `LiquidCoreiOS` directory in XCode (there is a test app which runs a node console), or you can build the framework on the command line with Carthage (`carthage build --no-skip-current`).

**Comment by ericwlange** [comment]
iOS support is now relatively complete in 0.5.0-experimental-6.  I will publish it on the front page with the full release 0.5.0, but it is good to go now.
