### ISSUE TITLE
Can a MicroService be used to transfer a file to the liquidserver ? 

### ISSUE THREAD

**Issue by alphaguy4** [LiquidPlayer/LiquidCore#63]
I wanted to change a file on the liquidcore server. Is it possible to do so .If yes then how ?

**Comment by ericwlange** [comment]
It wasn't really designed to do that.  LiquidServer is a pretty dumb server at this point.  I am probably going to switch to the [metro bundler](https://github.com/facebook/metro) fairly soon, as it does everything LiquidServer does but better and is more robust.

LiquidServer does just one thing -- it bundles up JavaScript files into a single file and makes it available to LiquidCore.

If you want to transfer files, you would use any traditional server setup and communicate with it through the typical [node API](https://nodejs.org/dist/latest-v8.x/docs/api/).

**Comment by alphaguy4** [comment]
apart from the given test apps example .any organisation is using Liquidcore ? What do you think can be the best usecase of using LiquidCore?

**Comment by ericwlange** [comment]
`liquidserver` is deprecated now in favor of the metro bundler.  Closing.

In a long overdue answer to your question, I see LiquidCore as the kernel of a native mobile operating environment.  My goal is to create an alternative to the app stores that acts more like the web (open, distributed, searchable, fast, small, secure and self-caching) but enables native access to the device's capabilities and OS (unlike with mobile web pages).

That requires a lot to be built on top of LiquidCore.  But for all that to work, you first need fast, instantiable cross-platform virtual machines.  Node.js was an obvious choice for that.  Its biggest challenge is that Node is not supported on iOS because of its dependence on V8, and is only barely supported on Android as it currently focused on the server world where Android is not a common OS.  LiquidCore solves that problem.

For now, I am happy to have developers use it in any way they see fit.  The vast majority of devs using it are only using it so they can have access to JavaScript without needing a WebView or to write code in C++.
