### ISSUE TITLE
JSContext properties aren't set if an ES2015 let is used.

### ISSUE THREAD

**Issue by jojo-apollo** [LiquidPlayer/LiquidCore#68]
The behaviour can be confirmed in the following code.
```Java
JSContext jsContext = new JSContext();

String varProperties = "" +
        "var objVar = {number:1,string:'string',date:new Date(),array:[1,'string',null,undefined],func:function(){}};" +
        "var noopVar = function(){}";
String letProperties = "" +
        "let objLet = {number:1,string:'string',date:new Date(),array:[1,'string',null,undefined],func:function(){}};" +
        "let noopLet = function(){}";

// Add the `var` variables
jsContext.evaluateScript(varProperties);
// Add the `let` variables
jsContext.evaluateScript(letProperties);

// This returns objVar and noopVar, ignoring objLet and noopLet.
String[] properties = jsContext.propertyNames();

// This will return undefined rather than the object.
jsContext.property("objLet");

// The only way to access the let variables is by an evaluateScript call.
String letObject = jsContext.evaluateScript("objLet").toObject().toJSON();
```

I'm not sure if this is intentional or not, just thought I'd raise an issue for it if it was a bug.

**Comment by ericwlange** [comment]
This is consistent with how node operates:
```
> var x = 1
undefined
> var y = 2
undefined
> let z = 3
undefined
> let w = 4
undefined
> x
1
> y
2
> global.x
1
> global.y
2
> z
3
> w
4
> global.z
undefined
> global.w
undefined
```

The [difference](https://www.geeksforgeeks.org/difference-between-var-and-let-in-javascript/) between `var` and `let` is that `var` is function-scoped where `let` is block scoped.  `JSContext` is not really an object.  When you treat it like one, it returns the global scope object which is why `var`s in the global scope will show up there.  `let` is block scoped, so it will only be available inside the `evaluateScript()` and then disappear once the execution is done.  Same is true for `const` as well.

**Comment by jojo-apollo** [comment]
Thanks for the clarification, I must've misread the documentation and code; I assumed `JSContext` was a block and the `property` function was just a fancy way to fetch variables within the given context.

This library is literally a godsend, and I appreciate you for making it.
