### ISSUE TITLE
Is it possible to build the library for node 10 instead of node 8.9.3?

### ISSUE THREAD

**Issue by stlpedro** [LiquidPlayer/LiquidCore#88]
Hi there,

Thank you so much for this great library. I wanted to know if it is possible to build it against nodejs 10.15.1 instead of nodejs 8.9.3.

Please let me know.

-Pedro

**Comment by ericwlange** [comment]
Yes, but it will take some work.  It is not simple to do.  It is on my backlog to upgrade to v10.x.  Do you mind me asking, what features are in v10 that you are looking for?

**Comment by stlpedro** [comment]
The error handling…. functions like process.setUncaughtExceptionCaptureCallback and such.

While on the subject of error handling… is there a way to turn on verbose errors reporting? I have a lot of crashes with no errors at all.

-Pedro

**Comment by ericwlange** [comment]
What do you get from `process.setUncaughtExceptionCaptureCallback` that you don't get from `process.on('uncaughtException', callback)`?  Just curious, because I've always used that.

What kinds of crashes are you getting?  Is it Android or iOS? I am surprised it possible to crash without getting anything in the logs.  There will be a stack trace in Dalvik (if you are on Android), even if it is cryptic.

**Comment by ericwlange** [comment]
0.7.x now uses 10.15.3
