### ISSUE TITLE
LiquidCore Android now requires android.permission.WRITE_EXTERNAL_STORAGE permission

### ISSUE THREAD

**Issue by jschnurholmes** [LiquidPlayer/LiquidCore#95]
After upgrading to version 0.6.0 of LiquidCored for Android, when I upload a new build of my app to the store, I get a warning that the app has a new permission, android.permission.WRITE_EXTERNAL_STORAGE, which users will have to accept before they can upgrade. Looking at my build/outputs/logs/manifest-merger-release-report.txt, this new permission is coming from LiquidCore-0.6.0.aar/3c0ca1e4e20da9b8b83eaffd57fed554/AndroidManifest.xml:12. LiquidCore did not previously require this permission. Is it necessary now? Is there a way to build without it?

**Comment by ericwlange** [comment]
Hmm, interesting.  LiquidCore has had that permission in its [`AndroidManifest.xml`](https://github.com/LiquidPlayer/LiquidCore/blob/master/LiquidCoreAndroid/src/main/AndroidManifest.xml) [since Jan 24, 2017](https://github.com/LiquidPlayer/LiquidCore/commit/361d5e85a88735d01ad3d4b70dbf669fbb137308#diff-5d1ed607d2afffce032cfcd6ced9f1cc).  Not sure how old of a version you are updating from.

However, if you are not using the public directories from the Node.js filesystem, then you shouldn't need that permission.  You can turn it off but just removing it from the manifest, but unfortunately you will have to use your own build of LiquidCore.  There is no exposed API method to do it.  Perhaps I can take that permission out by default in the next release.  If devs need it, they can add it to their own manifests.

Do you mind me asking what your app is (link)?  I am always eager to see how people are using it in production.

**Comment by consp1racy** [comment]
Until next version is released you can put this in your app's manifest

    <uses-permission tools:node="remove" android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

The practice is well described here: https://facebook.github.io/react-native/docs/removing-default-permissions

**Comment by ericwlange** [comment]
This has been made the default in 0.6.2.
